/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Dav(props) {
  const { nodes, materials } = useGLTF("/dav flor.gltf");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plano001.geometry}
        material={materials["Material.001"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plano002.geometry}
        material={materials["Material.001"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plano003.geometry}
        material={materials["Material.001"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Texto.geometry}
        material={materials["Material.001"]}
        position={[0.12, 0.01, -0.28]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Texto001.geometry}
        material={materials["Material.001"]}
        position={[0.63, 0.01, -0.02]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Texto002.geometry}
        material={materials["Material.001"]}
        position={[-0.49, 0.09, -0.26]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
      />
      <group position={[-0.01, 0.09, -0.01]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["tq_2_ARD-geom"].geometry}
          material={materials.tq_2_ARD_front}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["tq_2_ARD-geom_1"].geometry}
          material={materials.tq_2_ARD_back}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["tq_2_ARD-geom_2"].geometry}
          material={materials.tq_2_ARD_edge}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["tq_3_ARD-geom"].geometry}
        material={materials.tq_3_ARD_front}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["tq_3_ARD-geom_1"].geometry}
        material={materials.tq_3_ARD_back}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["tq_3_ARD-geom_2"].geometry}
        material={materials.tq_3_ARD_edge}
      />
    </group>
  );
}

useGLTF.preload("/dav flor.gltf");